# Generated by Django 5.2.5 on 2025-08-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('prioridade', models.CharField(choices=[('U', 'Urgente'), ('I', 'Importante'), ('N', 'Normal'), ('S', 'Sem prioridade')], default='N', max_length=1)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_fim', models.DateField()),
            ],
        ),
    ]
