# Generated by Django 5.2.5 on 2025-08-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataseventos',
            name='prioridade',
            field=models.CharField(choices=[('Urgente', 'Urgente'), ('Importante', 'Importante'), ('Normal', 'Normal'), ('Sem prioridade', 'Sem prioridade')], default='N', max_length=20),
        ),
    ]
