# Generated by Django 5.2.5 on 2025-08-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_dataseventos_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataseventos',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
