# Generated by Django 5.2.5 on 2025-08-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_dataseventos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataseventos',
            name='prioridade',
            field=models.CharField(choices=[('1', 'Urgente'), ('2', 'Importante'), ('3', 'Normal'), ('4', 'Sem prioridade')], default='N', max_length=20),
        ),
    ]
