# Generated by Django 5.2.5 on 2025-08-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='produto',
            name='main_produt_id_5f3016_idx',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='slug',
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['id'], name='main_produt_id_9d8d16_idx'),
        ),
    ]
