# Generated by Django 5.2.5 on 2025-08-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_produto_main_produt_id_5f3016_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='disponivel',
        ),
    ]
