# Generated by Django 5.2.7 on 2025-10-18 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('capacidade', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_hospede', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='main.quarto')),
            ],
        ),
    ]
