# Generated by Django 5.2.7 on 2025-10-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
