# Generated by Django 5.2.6 on 2025-12-24 01:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='O valor mínimo é 1')])),
                ('fim', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='O valor mínimo é 1')])),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='O valor mínimo é 1')])),
            ],
        ),
    ]
