# Generated by Django 5.2.6 on 2025-12-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortearprinci', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbers',
            name='gerarnovo',
            field=models.BooleanField(default=False),
        ),
    ]
