# Generated by Django 5.2.6 on 2025-12-24 02:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortearprinci', '0002_numbers_gerarnovo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='inicio',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='O valor mínimo é 0')]),
        ),
    ]
